pub struct AchievementDef {
    pub name: &'static str,
    pub display_name: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub score: i64,
    pub total: Option<f64>,
}

pub const ACHIEVEMENTS: &[AchievementDef] = &[
    AchievementDef {
        name: "first_steps",
        display_name: "First Steps",
        description: "Run 100m in a single run.",
        category: "Beginner",
        score: 10,
        total: Some(100.0),
    },
    AchievementDef {
        name: "night_owl",
        display_name: "Night Owl",
        description: "Run 1,000m in a single run.",
        category: "Silver",
        score: 50,
        total: Some(1000.0),
    },
    AchievementDef {
        name: "shadow_dancer",
        display_name: "Shadow Dancer",
        description: "Dash 50 times total across all runs.",
        category: "Bronze",
        score: 25,
        total: Some(50.0),
    },
    AchievementDef {
        name: "untouchable",
        display_name: "Untouchable",
        description: "Run 500m without taking any damage in a single run.",
        category: "Gold",
        score: 75,
        total: Some(500.0),
    },
    AchievementDef {
        name: "orb_hoarder",
        display_name: "Orb Hoarder",
        description: "Collect 500 Shadow Orbs total across all runs.",
        category: "Bronze",
        score: 25,
        total: Some(500.0),
    },
    AchievementDef {
        name: "close_call",
        display_name: "Close Call",
        description: "Get 10 near-miss bonuses in a single run.",
        category: "Gold",
        score: 75,
        total: Some(10.0),
    },
    AchievementDef {
        name: "speed_demon",
        display_name: "Speed Demon",
        description: "Reach maximum game speed.",
        category: "Gold",
        score: 100,
        total: None,
    },
    AchievementDef {
        name: "marathon_runner",
        display_name: "Marathon Runner",
        description: "Run 5,000m total across all runs.",
        category: "Silver",
        score: 50,
        total: Some(5000.0),
    },
    AchievementDef {
        name: "deathless_dash",
        display_name: "Deathless Dash",
        description: "Dash through 5 walls in a single run.",
        category: "Diamond",
        score: 100,
        total: Some(5.0),
    },
    AchievementDef {
        name: "midnight_legend",
        display_name: "Midnight Legend",
        description: "Score in the top 10 on the leaderboard.",
        category: "Diamond",
        score: 150,
        total: None,
    },
];
